Repository vtex-sites/nextjs.store, pull requests merged in 2022-11, with the labels that each got.

#273 feat: Adds `Carousel` component
  package.json
  src/components/ui/Carousel/Carousel.stories.mdx
  src/components/ui/Carousel/Carousel.tsx
  src/components/ui/Carousel/carousel.module.scss
  src/components/ui/Carousel/index.ts
  yarn.lock
Labels: Features, Refactoring

#297 fix: include necessary build dependencies with package
  package.json
Labels: Bug Fixes

#300 fix: specifies exact typescript version to avoid breaking changes
  package.json
  yarn.lock
Labels: Bug Fixes

#296 feat: `Icon` component.
  package.json
  yarn.lock
Labels: depends on

#210 Feat: Shipping Simulation API
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  bun.lockb
  package.json
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/ShippingSimulation/ShippingSimulation.tsx
  src/components/ui/ShippingSimulation/useShippingSimulation.ts
  src/sdk/shipping/index.ts
  yarn.lock
Labels: Features, depends on

#298 Feat: FSUI `Checkbox` component.
  package.json
  src/components/search/Filter/Facets.tsx
  src/components/ui/Checkbox/Checkbox.stories.mdx
  src/components/ui/Checkbox/Checkbox.tsx
  src/components/ui/Checkbox/checkbox.module.scss
  src/components/ui/Checkbox/index.ts
  yarn.lock
Labels: Features, depends on, Evergreen

#301 Chore: Removes Radio component
  src/components/ui/Radio/Radio.stories.mdx
  src/components/ui/Radio/Radio.tsx
  src/components/ui/Radio/index.ts
  src/components/ui/Radio/radio.module.scss
Labels: Chore, Evergreen
