Repository vtex-sites/nextjs.store, pull requests merged in 2022-12, with the labels that each got.

#311 Feat: FSUI `Overlay` component
  package.json
  src/components/ui/SlideOver/overlay.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
  yarn.lock
Labels: Evergreen

#313 Feat: Replaces `DiscountBadge` FSUI
  package.json
  src/components/product/ProductCard/ProductCard.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/Badge/Badge.stories.mdx
  src/components/ui/Badge/DiscountBadge.stories.mdx
  src/components/ui/Badge/DiscountBadge.tsx
  src/components/ui/Badge/badge.module.scss
  src/components/ui/Badge/index.ts
  src/components/ui/ProductTitle/ProductTitle.stories.mdx
  yarn.lock
Labels: Evergreen

#315 Feat: Replaces BuyButton FSUI
  package.json
  src/components/cart/CartSidebar/CartSidebar.stories.mdx
  src/components/product/ProductCard/ProductCard.stories.mdx
  src/components/product/ProductCard/ProductCard.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductDetails/product-details.module.scss
  src/components/sections/ScrollToTopButton/ScrollToTopButton.tsx
  src/components/ui/Button/Button.stories.mdx
  src/components/ui/Button/Button.tsx
  src/components/ui/Button/ButtonBuy/ButtonBuy.tsx
  src/components/ui/Button/ButtonBuy/index.ts
  src/components/ui/Button/ButtonLink/ButtonLink.tsx
  src/components/ui/Button/button.module.scss
  src/components/ui/Button/index.ts
  src/components/ui/SlideOver/SlideOver.stories.mdx
  yarn.lock
Labels: depends on, Evergreen

#316 Feat: Replaces `List` FSUI
  package.json
  src/components/common/Footer/Footer.tsx
  src/components/search/SearchHistory/SearchHistory.tsx
  src/components/search/SearchTop/SearchTop.tsx
  src/components/sections/Incentives/Incentives.tsx
  src/components/sections/ProducDetailsContent/ProductDetailsContent.tsx
  src/components/sections/ProducDetailsContent/product-details-content.module.scss
  yarn.lock
Labels: depends on, Evergreen

#314 Feat: Replaces `Select` FSUI
  src/components/search/Sort/Sort.tsx
  src/components/ui/Select/Select.stories.mdx
  src/components/ui/Select/Select.tsx
  src/components/ui/Select/index.ts
  src/components/ui/Select/select.module.scss
Labels: depends on, Evergreen

#317 Feat: Replaces `Link` FSUI
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/FooterLinks.tsx
  src/components/sections/BannerText/banner-text.module.scss
  src/components/ui/Button/ButtonLink/ButtonLink.tsx
  src/components/ui/Link/Link.tsx
  src/components/ui/Link/link.module.scss
  yarn.lock
Labels: depends on, Evergreen

#323 fix: Integration tests
  package.json
  yarn.lock
Labels: Bug Fixes, Tests

#322 chore: Replaces `LinkButton` UI
  .storybook/components/SectionItem.tsx
  .storybook/storybook.css
  src/components/common/Navbar/NavbarSlider.stories.mdx
  src/components/product/ProductCard/ProductCard.stories.mdx
  src/components/regionalization/Regionalization.stories.mdx
  src/components/regionalization/RegionalizationModal/RegionalizationModal.stories.mdx
  src/components/search/Filter/Filter.stories.mdx
  src/components/search/Filter/FilterSlider.stories.mdx
  src/components/search/SearchHistory/SearchHistory.stories.mdx
  src/components/sections/BannerText/BannerText.tsx
  src/components/sections/BannerText/banner-text.module.scss
  src/components/sections/Hero/Hero.tsx
  src/components/sections/ProductGallery/EmptyGallery.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/skeletons/Skeletons.stories.mdx
  src/components/ui/Accordion/Accordion.stories.mdx
  src/components/ui/Button/Button.stories.mdx
  src/components/ui/Button/ButtonLink/ButtonLink.tsx
  src/components/ui/Button/ButtonLink/index.ts
  src/components/ui/Button/ButtonSignIn/ButtonSignIn.tsx
  src/components/ui/Button/ButtonSignIn/ButtonSignInFallback/ButtonSignInFallback.tsx
  src/components/ui/Button/ButtonSignIn/ButtonSignInFallback/index.ts
  src/components/ui/Button/ButtonSignIn/index.ts
  src/components/ui/Button/index.ts
  src/components/ui/EmptyState/EmptyState.stories.mdx
  src/components/ui/Modal/Modal.stories.mdx
  src/components/ui/Toast/Toast.stories.mdx
  src/stories/brandless.stories.mdx
  src/stories/getting-started.stories.mdx
Labels: Evergreen
