Repository vtex-sites/nextjs.store, pull requests merged in 2022-10, with the labels that each got.

#265 fix: using data-fs instead data-store
  package.json
  src/components/common/Footer/footer.module.scss
  src/components/common/Navbar/navbar.module.scss
  src/components/product/OutOfStock/OutOfStock.tsx
  src/components/product/OutOfStock/out-of-stock.module.scss
  src/components/product/ProductCard/product-card.module.scss
  src/components/search/Filter/Facets.tsx
  src/components/search/SearchInput/search-input.module.scss
  src/components/sections/Incentives/incentives.module.scss
  src/components/sections/ProducDetailsContent/product-details-content.module.scss
  src/components/sections/ProductDetails/product-details.module.scss
  src/components/sections/ProductGallery/product-gallery.module.scss
  src/components/ui/Alert/alert.module.scss
  src/components/ui/Button/button.module.scss
  src/components/ui/InputText/input-text.module.scss
  src/components/ui/PriceRange/price-range.module.scss
  src/components/ui/ProductTitle/product-title.module.scss
  src/components/ui/QuantitySelector/quantity-selector.module.scss
  src/components/ui/SROnly/SROnly.tsx
  src/components/ui/SROnly/sr-only.scss
  src/components/ui/SkuSelector/sku-selector.module.scss
  yarn.lock
Labels: Bug Fixes

#272 chore: Change `resource-summary:stylesheet` metric to warning
  lighthouserc.js
Labels: Chore

#252 Feat: Adjust Newsletter to match new designs
  public/icons.svg
  src/components/sections/BannerNewsletter/BannerNewsletter.tsx
  src/components/sections/BannerNewsletter/banner-newsletter.module.scss
  src/components/sections/BannerText/banner-text.module.scss
  src/components/sections/Newsletter/Newsletter.stories.mdx
  src/components/sections/Newsletter/Newsletter.tsx
  src/components/sections/Newsletter/newsletter.module.scss
  src/components/ui/Toast/Toast.stories.mdx
  src/components/ui/Toast/Toast.stories.tsx
  src/components/ui/Toast/toast.module.scss
  src/pages/[slug]/p.tsx
  src/pages/index.tsx
Labels: Features, Style changes

#269 chore: use transition api to defer navbar behavior
  bun.lockb
  src/sdk/ui/useScrollDirection.ts
Labels: Performance

#276 chore: Renames CartToggle data-attr
  src/components/cart/CartToggle/CartToggle.tsx
  src/components/common/Navbar/navbar.module.scss
Labels: Chore

#271 Feat: Storybook Updates
  .storybook/storybook.css
  src/components/product/ProductCard/ProductCard.stories.mdx
  src/components/product/ProductCard/ProductCard.stories.tsx
  src/components/product/ProductCard/ProductCard.tsx
  src/components/product/ProductCard/product-card.module.scss
  src/components/ui/Badge/Badge.stories.mdx
  src/components/ui/Badge/Badge.stories.tsx
  src/components/ui/Badge/Badge.tsx
  src/components/ui/Badge/DiscountBadge.stories.mdx
  src/components/ui/Badge/DiscountBadge.stories.tsx
  src/components/ui/Badge/DiscountBadge.tsx
  src/components/ui/Badge/badge.module.scss
  src/components/ui/Badge/index.ts
  src/components/ui/Link/Link.stories.mdx
  src/components/ui/Link/Link.stories.tsx
  src/components/ui/Link/Link.tsx
  src/components/ui/Select/Select.stories.mdx
  src/components/ui/Select/Select.stories.tsx
  src/components/ui/Select/Select.tsx
  src/components/ui/Select/index.ts
  src/components/ui/Select/select.module.scss
  src/components/ui/Toast/Toast.stories.mdx
Labels: Documentation

#281 feat: Adds newsleter section
  src/components/cms/RenderPageSections.tsx
Labels: CMS

#275 doc: Updates documentation using Tokens components
  src/components/sections/BannerText/BannerText.stories.mdx
Labels: Documentation, Chore

#263 fix: collection pages facets
  package.json
  yarn.lock
Labels: Bug Fixes

#283 feat: Integrate CMS with PDP
  cms/content-types.json
  cms/sections.json
  src/components/cms/RenderPageSections.tsx
  src/components/sections/CrossSellingShelf/CrossSellingShelf.tsx
  src/components/sections/CrossSellingShelf/index.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/pages/[slug]/p.tsx
  src/pages/index.tsx
  src/server/cms.ts
Labels: Features, CMS

#293 chore: make store extendable
  bun.lockb
  package.json
  postinstall.js
  src/customizations/index.ts
  src/customizations/themes/index.scss
  src/pages/[slug]/p.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: Chore
