Repository vtex-sites/nextjs.store, pull requests merged in 2022-09, with the labels that each got.

#229 chore: Adds props description - Hero documentation (Storybook)
  src/components/sections/Hero/Hero.tsx
Labels: Documentation

#238 chore: move OrderSummary to FastStore UI
  bun.lockb
  package.json
  src/components/cart/OrderSummary/OrderSummary.tsx
  src/components/cart/OrderSummary/order-summary.module.scss
  src/components/cart/OrderSummary/order-summary.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
  yarn.lock
Labels: Chore

#239 refactor: Extract `CartItem` from the starter to `@faststore/ui`
  bun.lockb
  package.json
  src/components/cart/CartItem/CartItem.tsx
  yarn.lock
Labels: Refactoring

#240 refactor: Extract `SkuSelector` component to `@faststore/ui`
  bun.lockb
  src/components/ui/SkuSelector/SkuSelector.tsx
  src/components/ui/SkuSelector/index.ts
  yarn.lock
Labels: Refactoring

#242 fix: `view_item_list` event being fired without products
  cypress/integration/analytics.test.js
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductTiles/ProductTiles.tsx
  src/components/sections/Section/Section.tsx
  src/sdk/search/Sentinel.tsx
Labels: Bug Fixes

#236 Fix: Product Details Grid
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductDetails/product-details.module.scss
  src/components/sections/ProductDetails/product-details.scss
  src/components/ui/ImageGallery/ImageGallery.stories.mdx
  src/components/ui/ImageGallery/ImageGallery.tsx
  src/components/ui/ImageGallery/image-gallery.module.scss
  src/components/ui/ProductTitle/product-title.module.scss
  src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
  src/components/ui/ShippingSimulation/ShippingSimulation.tsx
  src/components/ui/ShippingSimulation/shipping-simulation.module.scss
  src/components/ui/SkuSelector/Selectors.tsx
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: Bug Fixes

#250 Fix: `ShippingSimulation` tokens
  src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
  src/components/ui/ShippingSimulation/shipping-simulation.module.scss
Labels: Bug Fixes

#251 fix: A regression with CLS on the Home page
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductTiles/ProductTiles.tsx
Labels: Bug Fixes

#247 feat: Fire `view_cart` event when the minicart is opened
  cypress/integration/analytics.test.js
  src/components/cart/CartSidebar/CartSidebar.tsx
Labels: Features

#254 fix: improve the execute server type
  src/server/index.ts
Labels: Bug Fixes

#255 fix: `ImageGallery` height on responsive views
  .storybook/storybook.css
  src/components/sections/ProductDetails/product-details.module.scss
  src/components/ui/ImageGallery/ImageGallery.stories.mdx
  src/components/ui/ImageGallery/image-gallery.module.scss
Labels: Bug Fixes

#260 feat: Add instant CMS Preview
  src/cms/client.ts
  src/pages/api/preview.ts
  src/pages/index.tsx
  src/server/cms.ts
Labels: Features

#258 feat: Create Product Details Content component
  bun.lockb
  package.json
  public/icons.svg
  src/components/search/Filter/Facets.stories.mdx
  src/components/search/Filter/facets.module.scss
  src/components/sections/ProducDetailsContent/ProductDetailsContent.stories.mdx
  src/components/sections/ProducDetailsContent/ProductDetailsContent.tsx
  src/components/sections/ProducDetailsContent/index.tsx
  src/components/sections/ProducDetailsContent/product-details-content.module.scss
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductDetails/product-details.module.scss
  src/components/ui/Accordion/Accordion.stories.mdx
  src/components/ui/Accordion/AccordionItem.stories.mdx
  src/components/ui/Accordion/AccordionItem.tsx
  src/components/ui/Accordion/accordion.module.scss
  yarn.lock
Labels: Features
