Repository vtex-sites/nextjs.store, pull requests merged in 2022-08, with the labels that each got.

#187 feat: Add `ProductTitle` import from faststore
  CHANGELOG.md
  package.json
  src/components/ui/ProductTitle/ProductTitle.stories.mdx
  src/components/ui/ProductTitle/ProductTitle.tsx
  src/components/ui/ProductTitle/product-title.module.scss
  yarn.lock
Labels: enhancement

#146 Feat: adds tokens to `PriceRange`
  CHANGELOG.md
  src/components/ui/InputText/input-text.scss
  src/components/ui/PriceRange/PriceRange.stories.mdx
  src/components/ui/PriceRange/PriceRange.tsx
  src/components/ui/PriceRange/price-range.module.scss
  src/sdk/product/useFormattedPrice.ts
  src/styles/global/tokens.scss
Labels: documentation, enhancement

#195 fix: Attempt to fix automated changelog update
  bun.lockb
  pull_request_template.md
Labels: Bug Fixes

#196 fix: Attempt to fix the automated changelog update
  .github/workflows/release.yml
Labels: Bug Fixes

#193 fix: Avoids performing the search when user abandons the query [FS-243]
  src/components/common/Navbar/Navbar.tsx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchInput/index.tsx
Labels: Bug Fixes

#198 chore: Updates `BannerText` content example
  src/components/sections/BannerText/BannerText.stories.mdx
  src/pages/index.tsx
Labels: Chore

#158 feat: Working `SkuSelector` component
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  package.json
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/SkuSelector/Selectors.tsx
  src/components/ui/SkuSelector/SkuSelector.tsx
  src/components/ui/SkuSelector/index.tsx
  src/components/ui/SkuSelector/sku-selector.scss
  src/components/ui/SkuSelector/skuVariants.ts
  src/styles/global/components.scss
  yarn.lock
Labels: Features

#185 refactor: Import `Tiles` & `Tile` components from `@faststore/ui`
  bun.lockb
  src/components/ui/Tiles/Tile.tsx
  src/components/ui/Tiles/Tiles.tsx
  src/components/ui/Tiles/index.ts
Labels: Chore

#189 feat: Add new tokens to `SearchInput` [FS-496]
  src/components/common/Navbar/navbar.module.scss
  src/components/search/SearchInput/SearchInput.stories.mdx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchInput/search-input.module.scss
  src/components/search/SearchInput/search-input.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: Features

#191 Feat: Refinements on `Navbar` and `Navlinks`
  src/components/common/Navbar/NavLinks.stories.mdx
  src/components/common/Navbar/NavLinks.tsx
  src/components/common/Navbar/Navbar.stories.mdx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/navbar.module.scss
  src/components/common/Navbar/navlinks.module.scss
  src/sdk/ui/useScrollDirection.ts
  src/styles/global/tokens.scss
Labels: Documentation, Features

#201 fix: Cart promotions & more
  @generated/graphql/index.ts
  package.json
  src/components/cart/CartItem/CartItem.tsx
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/sdk/cart/index.ts
  yarn.lock
Labels: Bug Fixes

#200 feat: Handles `OutOfStock` error message through `InputText`'s `error` prop [FS-240]
  src/components/product/OutOfStock/OutOfStock.tsx
Labels: Features

#203 Chore: Adds `InputText` documentation to storybook
  src/components/ui/InputText/InputText.stories.mdx
  src/components/ui/InputText/InputText.stories.tsx
  src/components/ui/InputText/InputText.tsx
  src/components/ui/InputText/input-text.module.scss
  src/components/ui/InputText/input-text.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: Documentation, Chore

#207 feat: Product releaseDate
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  package.json
  src/pages/[slug]/p.tsx
  yarn.lock
Labels: Bug Fixes, Features

#202 feat: Add new tokens to `SkuSelector` [FS-379]
  src/components/ui/SkuSelector/Selectors.stories.mdx
  src/components/ui/SkuSelector/Selectors.tsx
  src/components/ui/SkuSelector/SkuSelector.stories.mdx
  src/components/ui/SkuSelector/SkuSelector.tsx
  src/components/ui/SkuSelector/index.ts
  src/components/ui/SkuSelector/sku-selector.module.scss
  src/components/ui/SkuSelector/sku-selector.scss
  src/styles/global/components.scss
Labels: Features

#208 chore: Renames/Updates border tokens
  src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
  src/components/ui/ShippingSimulation/shipping-simulation.module.scss
  src/stories/refinements.stories.mdx
  src/styles/global/tokens.scss
Labels: Chore

#212 fix: Display `SearchDropdown` correctly
  .storybook/storybook.css
  src/components/common/Navbar/navlinks.module.scss
Labels: Bug Fixes

#209 chore: Renames/Updates breakpoints tokens
  src/components/sections/Hero/hero.scss
  src/stories/typography.stories.mdx
  src/styles/global/tokens.scss
Labels: Documentation, Chore

#205 Feat: integrate with client-cms
  README.md
  cms-webhook-urls.json
  cms/content-types.json
  cms/sections.json
  cms/translation-keys.json
  package.json
  src/cms/client.ts
  src/components/cms/RenderPageSections.tsx
  src/pages/index.tsx
  store.config.js
  yarn.lock
Labels: Features

#214 fix: Fix cms config
  cms/sections.json
Labels: Bug Fixes

#213 chore: Include `Button` with only an icon on Storybook
  .storybook/storybook.css
  src/components/ui/Button/Button.stories.mdx
  src/components/ui/Button/button.module.scss
Labels: Documentation, Chore

#215 chore: Updates border values to px
  src/stories/refinements.stories.mdx
  src/styles/global/tokens.scss
Labels: Chore

#217 chore: Revisit `Hero` documentation (Storybook)
  src/components/sections/Hero/Hero.stories.mdx
  src/components/sections/Hero/Hero.stories.tsx
  src/components/sections/Hero/Hero.tsx
  src/components/sections/Hero/hero.module.scss
  src/components/sections/Hero/hero.scss
  src/components/sections/Hero/index.ts
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: Documentation, Chore

#224 fix: Navigation links on mobile not being clickable
  src/components/common/Navbar/navlinks.module.scss
Labels: Bug Fixes
