Repository vtex-sites/nextjs.store, pull requests merged in 2022-05, with the labels that each got.

#13 chore: Better organize the Changelog
  CHANGELOG.md
Labels: chore

#12 chore: Show more details about failed accessibility tests
  CHANGELOG.md
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
Labels: chore

#32 fix: Promotions
  package.json
  src/server/index.ts
  yarn.lock
Labels: bug

#39 feat: Incremental Static Build
  CHANGELOG.md
  vtex.env
Labels: enhancement, performance

#35 Feat/add analytics to cart item
  CHANGELOG.md
  src/components/cart/CartItem/CartItem.tsx
Labels: enhancement

#20 chore: Rename Badge prop
  CHANGELOG.md
  src/components/ui/Badge/Badge.stories.tsx
  src/components/ui/Badge/Badge.tsx
  src/components/ui/Badge/badge.scss
Labels: chore

#40 fix: storybook build - removes unused import
  CHANGELOG.md
  src/styles/global/storybook-components.scss
Labels: bug

#11 fix: Remove incorrect vertical gap for the cart empty state
  CHANGELOG.md
  cypress/integration/cart.test.js
  src/components/common/Navbar/navbar.scss
  src/components/sections/ProductGallery/EmptyGallery.tsx
  src/components/sections/ProductGallery/product-gallery.module.scss
  src/components/ui/EmptyState/EmptyState.tsx
  src/components/ui/EmptyState/empty-state.scss
Labels: bug

#44 fix: Breadcrumb broken links
  package.json
  yarn.lock
Labels: bug

#49 Improve LCP by setting a higher fetch priority
  CHANGELOG.md
  src/components/sections/Hero/Hero.tsx
  src/components/ui/Image/Image.tsx
  src/components/ui/ImageGallery/ImageGallery.tsx
Labels: performance

#51 chore: Removes `default` nomenclature from global tokens
  CHANGELOG.md
  README.md
  src/components/cart/CartItem/cart-item.scss
  src/components/common/Footer/footer.scss
  src/components/common/Navbar/navbar.scss
  src/components/common/SearchInput/search-input.scss
  src/components/product/ProductCard/product-card.scss
  src/components/regionalization/RegionalizationButton/regionalization-button.scss
  src/components/search/Filter/filter.scss
  src/components/search/SuggestionProductCard/suggestion-product-card.module.scss
  src/components/search/Suggestions/suggestions.module.scss
  src/components/sections/ProductDetails/product-details.scss
  src/components/sections/Section/section.scss
  src/components/skeletons/FilterSkeleton/filter-skeleton.scss
  src/components/skeletons/ProductCardSkeleton/product-card-skeleton.scss
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/product-tile-skeleton.scss
  src/components/skeletons/SkeletonElement/skeleton-element.scss
  src/components/ui/Badge/badge.scss
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Button/button.scss
  src/components/ui/Checkbox/checkbox.scss
  src/components/ui/EmptyState/empty-state.scss
  src/components/ui/ImageGallery/image-gallery-selector.module.scss
  src/components/ui/ImageGallery/image-gallery.module.scss
  src/components/ui/InputText/input-text.scss
  src/components/ui/Link/link.scss
  src/components/ui/QuantitySelector/quantity-selector.scss
  src/components/ui/Select/select.scss
  src/components/ui/SkuSelector/sku-selector.scss
  src/components/ui/Tiles/tiles.scss
  src/styles/global/tokens.scss
  src/styles/global/utilities.scss
Labels: chore

#45 chore: Improve home performance
  CHANGELOG.md
  package.json
  src/components/common/Navbar/Navbar.tsx
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductTiles/ProductTiles.tsx
  src/components/ui/Button/ButtonSignIn.tsx
  src/components/ui/Button/ButtonSignInFallback.tsx
  src/components/ui/Button/index.tsx
  src/pages/index.tsx
  src/sdk/graphql/useQuery.ts
  src/sdk/person/usePersonQuery.ts
  src/sdk/product/useProductsQuery.ts
  yarn.lock
Labels: enhancement, performance

#53 fix: Fixes SCSS import for CSS modules
  .storybook/main.js
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug

#60 fix: Fixes custom attributes for img and link tags
  CHANGELOG.md
  src/components/ui/Image/Image.tsx
Labels: bug

#65 fix: Fixes <link /> attribute typo
  src/components/ui/Image/Image.tsx
Labels: bug

#66 chore: add tests to cart analytics
  CHANGELOG.md
  cypress/integration/analytics.test.js
  src/components/ui/QuantitySelector/QuantitySelector.tsx
Labels: chore

#67 Feat: Unify Storybook Documentation
  .storybook/preview.js
  .storybook/storybook.css
  .storybook/theme.js
  CHANGELOG.md
  src/components/product/ProductCard/product-card.scss
  src/components/sections/BannerText/BannerText.stories.mdx
  src/components/sections/BannerText/BannerText.stories.tsx
  src/components/sections/BannerText/banner-text.scss
  src/components/ui/Hero/hero.scss
  src/components/ui/InputText/input-text.scss
  src/components/ui/Toggle/Toggle.stories.mdx
  src/components/ui/Toggle/Toggle.stories.tsx
  src/components/ui/Toggle/Toggle.tsx
  src/components/ui/Toggle/toggle.scss
  src/stories/colors.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/icons.stories.mdx
  src/stories/theming.stories.mdx
  src/stories/typography.stories.mdx
  src/styles/global/tokens.scss
Labels: documentation, chore

#77 Doc: fixed doc responsible names
  pull_request_template.md
Labels: documentation
