Repository vtex-sites/nextjs.store, pull requests merged in 2022-07, with the labels that each got.

#142 Feat: Adds tokens to `Navbar`
  .storybook/storybook.css
  CHANGELOG.md
  README.md
  src/components/common/Navbar/NavLinks.stories.mdx
  src/components/common/Navbar/NavLinks.tsx
  src/components/common/Navbar/Navbar.stories.mdx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/NavbarSlider.stories.mdx
  src/components/common/Navbar/NavbarSlider.tsx
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/navbar-slider.module.scss
  src/components/common/Navbar/navbar.module.scss
  src/components/common/Navbar/navbar.scss
  src/components/common/Navbar/navlinks.module.scss
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignIn.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignInFallback/ButtonSignInFallback.tsx
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: documentation, enhancement

#151 Feat: Add tokens to `SuggestionProductCard`
  .storybook/mock/index.ts
  .storybook/mock/product.ts
  CHANGELOG.md
  src/components/search/History/SearchHistory.stories.tsx
  src/components/search/SuggestionProductCard/SuggestionProductCard.stories.mdx
  src/components/search/SuggestionProductCard/SuggestionProductCard.tsx
  src/components/search/SuggestionProductCard/suggestion-product-card.module.scss
  src/components/search/SuggestionProductCard/suggestion-product-card.scss
  src/components/search/Suggestions/SuggestionsTopSearch.stories.tsx
  src/components/ui/Search/Suggestions/Suggestions.stories.tsx
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
  src/styles/global/tokens.scss
Labels: documentation, enhancement

#156 Unifies the mocks folder
  .storybook/mock/index.ts
  .storybook/mocks/index.ts
  .storybook/mocks/product.ts
  .storybook/mocks/productGridItems.ts
  CHANGELOG.md
  src/components/product/ProductGrid/ProductGrid.stories.mdx
  src/components/search/SuggestionProductCard/SuggestionProductCard.stories.mdx
Labels: chore

#160 chore: Upgrade Next.JS
  package.json
  yarn.lock
Labels: enhancement

#164 feat: Bun compatibility
  CHANGELOG.md
  bun.lockb
  package.json
  yarn.lock
Labels: performance

#161 feat: Add priceCurrency to Offer
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement

#147 Chore: Storybook Docs Updates
  .storybook/storybook.css
  CHANGELOG.md
  src/components/cart/CartItem/CartItem.stories.mdx
  src/components/product/ProductCard/ProductCard.stories.tsx
  src/components/regionalization/RegionalizationModal/RegionalizationModal.stories.mdx
  src/components/search/Filter/Filter.stories.mdx
  src/components/sections/Hero/Hero.stories.tsx
  src/components/ui/Badge/Badge.stories.tsx
  src/components/ui/Badge/DiscountBadge.stories.tsx
  src/components/ui/Button/Button.stories.mdx
  src/components/ui/Dropdown/Dropdown.stories.mdx
  src/components/ui/EmptyState/EmptyState.stories.mdx
  src/components/ui/InputText/InputText.stories.tsx
  src/components/ui/Link/Link.stories.tsx
  src/components/ui/PriceRange/PriceRange.stories.mdx
  src/components/ui/ProductTitle/ProductTitle.stories.mdx
  src/components/ui/QuantitySelector/QuantitySelector.stories.mdx
  src/components/ui/Select/Select.stories.tsx
  src/components/ui/Toast/Toast.stories.tsx
  src/stories/changelog-template.stories.mdx
  src/stories/colors.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/global-tokens.stories.mdx
  src/stories/icons.stories.mdx
  src/stories/theming.stories.mdx
  src/styles/global/tokens.scss
Labels: documentation, chore

#162 Feat: Adds new tokens to `Breadcrumb`
  CHANGELOG.md
  public/icons.svg
  src/components/ui/Breadcrumb/Breadcrumb.stories.mdx
  src/components/ui/Breadcrumb/Breadcrumb.stories.tsx
  src/components/ui/Breadcrumb/Breadcrumb.tsx
  src/components/ui/Breadcrumb/breadcrumb.module.scss
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Dropdown/DropdownItem.stories.mdx
  src/components/ui/Dropdown/DropdownItem.tsx
  src/components/ui/Dropdown/dropdown.module.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: documentation, enhancement

#163 fix: Transfers responsibility of `InputText`'s main attributes and callbacks to the renderer
  CHANGELOG.md
  src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
  src/components/ui/InputText/InputText.stories.tsx
  src/components/ui/InputText/InputText.tsx
Labels: bug

#155 Feat: adds tokens to `Footer`
  .storybook/components/SectionItem.tsx
  .storybook/storybook.css
  CHANGELOG.md
  src/components/common/Footer/Footer.stories.mdx
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/FooterLinks.tsx
  src/components/common/Footer/footer.module.scss
  src/components/common/Footer/footer.scss
  src/components/sections/Incentives/Incentives.stories.mdx
  src/components/sections/Incentives/Incentives.tsx
  src/components/sections/Incentives/IncentivesFooter.tsx
  src/components/sections/Incentives/incentives.module.scss
  src/components/sections/Incentives/incentivesMock.js
  src/components/sections/Incentives/incentivesMock.ts
  src/pages/index.tsx
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: documentation, enhancement

#169 Fix: SonarQube and tests
  CHANGELOG.md
  src/components/ui/Modal/Modal.tsx
Labels: chore

#177 chore: Improve integration tests by upgrading Cypress to 9.6.5
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#173 Feat: Add css modules, tokens and refactor `Search` components
  .storybook/components/SectionItem.tsx
  .storybook/mocks/index.ts
  .storybook/mocks/searchHistory.ts
  .storybook/mocks/searchTerms.ts
  CHANGELOG.md
  src/components/common/Navbar/Navbar.tsx
  src/components/common/SearchInput/index.tsx
  src/components/search/History/SearchHistory.stories.tsx
  src/components/search/Search.stories.mdx
  src/components/search/SearchDropdown/SearchDropdown.stories.mdx
  src/components/search/SearchDropdown/SearchDropdown.tsx
  src/components/search/SearchDropdown/index.ts
  src/components/search/SearchHistory/SearchHistory.stories.mdx
  src/components/search/SearchHistory/SearchHistory.tsx
  src/components/search/SearchHistory/index.tsx
  src/components/search/SearchInput/SearchInput.stories.mdx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchInput/index.tsx
  src/components/search/SearchInput/search-input.scss
  src/components/search/SearchProductCard/SearchProductCard.stories.mdx
  src/components/search/SearchProductCard/SearchProductCard.tsx
  src/components/search/SearchProductCard/index.ts
  src/components/search/SearchProductCard/search-product-card.module.scss
  src/components/search/SearchSharedTokenTable.mdx
  src/components/search/SearchSuggestions/SearchSuggestions.stories.mdx
  src/components/search/SearchSuggestions/SearchSuggestions.tsx
  src/components/search/SearchSuggestions/index.ts
  src/components/search/SearchTop/SearchTop.stories.mdx
  src/components/search/SearchTop/SearchTop.tsx
  src/components/search/SearchTop/index.ts
  src/components/search/SuggestionProductCard/index.ts
  src/components/search/SuggestionProductCard/suggestion-product-card.module.scss
  src/components/search/Suggestions/Suggestions.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.stories.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.tsx
  src/components/search/Suggestions/index.ts
  src/components/search/Suggestions/suggestions.scss
  src/components/search/search.module.scss
  src/components/search/searchMock.ts
  src/components/ui/Search/Suggestions/Suggestions.stories.tsx
  src/components/ui/Search/Suggestions/index.ts
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: documentation, enhancement

#175 Feat: Theming Adjustments
  .storybook/components/SectionList.tsx
  .storybook/storybook.css
  CHANGELOG.md
  src/components/cart/CartSidebar/CartSidebar.stories.mdx
  src/components/cart/CartToggle/cart-toggle.scss
  src/components/common/Navbar/NavLinks.stories.mdx
  src/components/common/Navbar/Navbar.stories.mdx
  src/components/common/Navbar/NavbarSlider.stories.mdx
  src/components/product/ProductCard/product-card.module.scss
  src/components/search/Filter/FilterSlider.stories.mdx
  src/components/sections/ProductGallery/product-gallery.module.scss
  src/components/ui/SlideOver/SlideOver.stories.mdx
  src/components/ui/Tiles/tiles.module.scss
  src/fonts/WebFonts.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/stories/customizing.stories.mdx
  src/stories/interactive-controls.stories.mdx
  src/stories/midnight.stories.mdx
  src/stories/soft-blue.stories.mdx
  src/stories/typography.stories.mdx
  src/styles/global/tokens.scss
  src/styles/themes/custom-theme.scss
Labels: documentation, enhancement

#182 chore: Improve integration tests by upgrading Cypress to 9.6.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#171 feat: Adds new tokens to `Skeleton`
  .storybook/storybook.css
  CHANGELOG.md
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/ProductGallery/product-gallery.module.scss
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductShelf/product-shelf.module.scss
  src/components/skeletons/FilterSkeleton/FilterSkeleton.stories.mdx
  src/components/skeletons/FilterSkeleton/FilterSkeleton.tsx
  src/components/skeletons/FilterSkeleton/filter-skeleton.module.scss
  src/components/skeletons/FilterSkeleton/filter-skeleton.scss
  src/components/skeletons/ProductCardSkeleton/ProductCardSkeleton.stories.mdx
  src/components/skeletons/ProductCardSkeleton/ProductCardSkeleton.tsx
  src/components/skeletons/ProductCardSkeleton/product-card-skeleton.module.scss
  src/components/skeletons/ProductCardSkeleton/product-card-skeleton.scss
  src/components/skeletons/ProductGridSkeleton/ProductGridSkeleton.tsx
  src/components/skeletons/ProductShelfSkeleton/ProductShelfSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/ProductTileSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/product-tile-skeleton.module.scss
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/product-tile-skeleton.scss
  src/components/skeletons/ProductTilesSkeleton/ProductTilesSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/index.ts
  src/components/skeletons/Shimmer/Shimmer.tsx
  src/components/skeletons/Shimmer/shimmer.module.scss
  src/components/skeletons/Shimmer/shimmer.scss
  src/components/skeletons/Skeleton/Skeleton.tsx
  src/components/skeletons/Skeleton/index.ts
  src/components/skeletons/Skeleton/skeleton.module.scss
  src/components/skeletons/SkeletonElement/SkeletonElement.tsx
  src/components/skeletons/SkeletonElement/index.ts
  src/components/skeletons/SkeletonElement/skeleton-element.scss
  src/components/skeletons/Skeletons.stories.mdx
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: enhancement

#184 chore: add automatic changelog
  .github/workflows/release.yml
  .release-it.json
  CHANGELOG.md
  bun.lockb
  package.json
  pull_request_template.md
Labels: chore

#186 chore: update release workflow to use bun
  .github/workflows/release.yml
Labels: chore
