Repository vtex-sites/nextjs.store, pull requests merged in 2022-06, with the labels that each got.

#81 feat: Add document in QuantitySelector
  .storybook/components/TokenDivider.tsx
  .storybook/components/TokenRow.tsx
  .storybook/components/TokenTable.tsx
  .storybook/components/index.ts
  CHANGELOG.md
  src/components/ui/QuantitySelector/QuantitySelector.stories.mdx
Labels: documentation, chore

#82 chore: Style Toast
  CHANGELOG.md
  public/icons.svg
  src/Layout.tsx
  src/components/ui/Toast/Toast.stories.tsx
  src/components/ui/Toast/Toast.tsx
  src/components/ui/Toast/toast.module.scss
  src/sdk/ui/index.tsx
Labels: chore

#89 fix: lighthouse complaining about robots.txt
  CHANGELOG.md
  public/robots.txt
Labels: bug

#88 fix: Static incremental builds errors
  CHANGELOG.md
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
Labels: bug

#87 Feat: Adds tokens to `Radio`
  .storybook/storybook.css
  CHANGELOG.md
  src/components/ui/Checkbox/Checkbox.stories.mdx
  src/components/ui/Checkbox/checkbox.module.scss
  src/components/ui/Radio/Radio.stories.mdx
  src/components/ui/Radio/Radio.tsx
  src/components/ui/Radio/index.tsx
  src/components/ui/Radio/radio.module.scss
Labels: enhancement, chore

#98 Feat: Uses Hero component from FSUI
  CHANGELOG.md
  package.json
  src/components/sections/Hero/Hero.tsx
  src/components/sections/Hero/hero.scss
  src/components/ui/Hero/Hero.tsx
  src/components/ui/Hero/HeroContent.tsx
  src/components/ui/Hero/HeroImage.tsx
  src/components/ui/Hero/HeroLink.tsx
  src/components/ui/Hero/index.ts
  src/pages/index.tsx
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
  yarn.lock
Labels: chore

#94 Feat: Adds tokens to `Alert`
  CHANGELOG.md
  src/components/ui/Alert/Alert.stories.mdx
  src/components/ui/Alert/Alert.tsx
  src/components/ui/Alert/alert.module.scss
  src/components/ui/Alert/alert.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: enhancement, chore

#99 feat: Refactors `Button` component
  .storybook/storybook.css
  CHANGELOG.md
  src/components/sections/ProductDetails/product-details.scss
  src/components/sections/ScrollToTopButton/ScrollToTopButton.tsx
  src/components/ui/Button/Button.stories.mdx
  src/components/ui/Button/Button.tsx
  src/components/ui/Button/ButtonBuy.tsx
  src/components/ui/Button/ButtonBuy/ButtonBuy.tsx
  src/components/ui/Button/ButtonBuy/index.ts
  src/components/ui/Button/ButtonIcon.tsx
  src/components/ui/Button/ButtonLink/ButtonLink.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignIn.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/index.ts
  src/components/ui/Button/ButtonLink/index.ts
  src/components/ui/Button/button.module.scss
  src/components/ui/Button/index.tsx
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: chore

#31 feat: Adjust Alert for CMS
  CHANGELOG.md
  public/icons.svg
  src/Layout.tsx
  src/components/common/Alert/Alert.tsx
Labels: enhancement

#106 Chore: Improves rows and dividers on storybook
  .storybook/components/TokenDivider.tsx
  .storybook/storybook.css
  CHANGELOG.md
Labels: chore

#107 Chore: Adds `--docs` to storybook script
  CHANGELOG.md
  package.json
Labels: chore

#103 chore: Sync components' code
  CHANGELOG.md
  src/Layout.tsx
  src/components/common/SearchInput/SearchInput.tsx
  src/components/product/ProductCard/product-card.module.scss
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignInFallback/ButtonSignInFallback.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignInFallback/index.ts
  src/components/ui/Button/index.ts
  src/components/ui/EmptyState/EmptyState.tsx
  src/components/ui/Toggle/toggle.scss
Labels: chore

#97 Feat: Adds tokens to `OutOfStock`
  CHANGELOG.md
  src/components/product/OutOfStock/OutOfStock.stories.mdx
  src/components/product/OutOfStock/OutOfStock.tsx
  src/components/product/OutOfStock/out-of-stock.module.scss
  src/components/product/OutOfStock/out-of-stock.scss
  src/components/sections/ProductDetails/product-details.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
  src/styles/global/tokens.scss
Labels: documentation, enhancement

#108 fix: Region Input
  CHANGELOG.md
  src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
Labels: bug

#101 Feat: Best Practices Section
  .storybook/components/BestPractices.tsx
  .storybook/components/BestPracticesRule.tsx
  .storybook/components/TokenRow.tsx
  .storybook/components/index.ts
  .storybook/storybook.css
  CHANGELOG.md
  src/components/ui/Alert/Alert.stories.mdx
  src/components/ui/Alert/Alert.tsx
  src/components/ui/Button/Button.stories.mdx
Labels: documentation, enhancement

#100 chore: Single UI Provider
  CHANGELOG.md
  src/Layout.tsx
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Toast/Toast.tsx
  src/components/regionalization/RegionalizationBar/RegionalizationBar.tsx
  src/components/regionalization/RegionalizationButton/RegionalizationButton.tsx
  src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
  src/components/regionalization/RegionalizationModal/RegionalizationModal.tsx
  src/components/search/Filter/Filter.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/ui/SlideOver/SlideOver.tsx
  src/components/ui/Toast/Toast.stories.tsx
  src/components/ui/Toast/Toast.tsx
  src/pages/_app.tsx
  src/sdk/cart/useBuyButton.ts
  src/sdk/cart/useCartToggleButton.ts
  src/sdk/ui/Provider.tsx
  src/sdk/ui/index.tsx
  src/sdk/ui/modal/Provider.tsx
  src/sdk/ui/modal/index.ts
  src/sdk/ui/useFadeEffect.ts
Labels: enhancement

#111 fix: Spot pricing sort for lowPrice/highPrice
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug

#113 chore: Add support new types from React 18
  CHANGELOG.md
  package.json
  src/components/sections/Hero/Hero.stories.tsx
  src/sdk/error/ErrorBoundary/ErrorBoundary.tsx
  yarn.lock
Labels: chore

#116 fix: Page error codes
  CHANGELOG.md
  package.json
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
  src/pages/api/graphql.ts
  src/server/index.ts
  yarn.lock
Labels: bug

#93 feat: Canonical PDP slugs
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  package.json
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
  src/server/index.ts
  store.config.js
  yarn.lock
Labels: enhancement

#117 chore: Unify Link usage
  CHANGELOG.md
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/footer.scss
  src/components/common/Link/Link.tsx
  src/components/common/Link/index.ts
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/navbar.scss
  src/components/common/SearchInput/search-input.scss
  src/components/product/ProductCard/ProductCard.tsx
  src/components/product/ProductCard/product-card.module.scss
  src/components/regionalization/RegionalizationModal/regionalization-modal.scss
  src/components/search/Suggestions/suggestions.scss
  src/components/sections/BannerText/banner-text.scss
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/ui/Alert/Alert.tsx
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Button/ButtonLink/ButtonLink.tsx
  src/components/ui/EmptyState/empty-state.scss
  src/components/ui/Link/Link.tsx
Labels: chore

#120 chore: Upgrade Storybook from 6.4.20 to 6.5.9
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#118 Feat: Extract and adds tokens to Dropdown
  .storybook/storybook.css
  CHANGELOG.md
  public/icons.svg
  src/components/ui/Breadcrumb/Breadcrumb.tsx
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Dropdown/Dropdown.stories.mdx
  src/components/ui/Dropdown/Dropdown.tsx
  src/components/ui/Dropdown/DropdownButton.tsx
  src/components/ui/Dropdown/DropdownItem.stories.mdx
  src/components/ui/Dropdown/DropdownItem.tsx
  src/components/ui/Dropdown/DropdownMenu.stories.mdx
  src/components/ui/Dropdown/DropdownMenu.tsx
  src/components/ui/Dropdown/dropdown.module.scss
  src/components/ui/Dropdown/index.tsx
Labels: chore

#122 Feat: Adds tokens to `EmptyState`
  CHANGELOG.md
  src/components/cart/EmptyCart/EmptyCart.stories.mdx
  src/components/cart/EmptyCart/EmptyCart.tsx
  src/components/sections/ProductGallery/EmptyGallery.stories.mdx
  src/components/sections/ProductGallery/EmptyGallery.tsx
  src/components/ui/EmptyState/EmptyState.stories.mdx
  src/components/ui/EmptyState/EmptyState.tsx
  src/components/ui/EmptyState/empty-state.module.scss
  src/components/ui/EmptyState/empty-state.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: documentation, enhancement, chore

#126 Chore: `EmptyState` Use Cases section
  CHANGELOG.md
  src/components/cart/EmptyCart/EmptyCart.stories.mdx
  src/components/sections/ProductGallery/EmptyGallery.stories.mdx
  src/components/ui/EmptyState/EmptyState.stories.mdx
Labels: enhancement, chore

#123 Fix: Sync Dropdown and Breadcrumb components
  CHANGELOG.md
  src/components/ui/Breadcrumb/Breadcrumb.stories.tsx
  src/components/ui/Breadcrumb/breadcrumb.scss
Labels: chore

#112 feat: Add search history & top searches
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  src/components/common/Navbar/navbar.scss
  src/components/common/SearchInput/SearchInput.tsx
  src/components/common/SearchInput/search-input.scss
  src/components/search/History/SearchHistory.stories.tsx
  src/components/search/History/SearchHistory.tsx
  src/components/search/SuggestionProductCard/SuggestionProductCard.tsx
  src/components/search/SuggestionProductCard/suggestion-product-card.scss
  src/components/search/Suggestions/Suggestions.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.stories.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.tsx
  src/components/search/Suggestions/suggestions.scss
  src/components/ui/Search/Suggestions/Suggestions.stories.tsx
  src/components/ui/Search/Suggestions/Suggestions.tsx
  src/sdk/search/useSearchHistory.ts
  src/sdk/search/useSearchInput.tsx
  src/sdk/search/useSuggestions.ts
  src/sdk/search/useTopSearch.ts
Labels: enhancement

#131 chore: Upgrade dependencies
  .babelrc
  .storybook/main.js
  CHANGELOG.md
  codegen.yml
  lighthouserc.js
  package.json
  src/components/product/ProductCard/ProductCard.tsx
  src/components/search/Filter/Filter.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductGallery/useGalleryQuery.ts
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
  src/sdk/cart/validate.ts
  src/sdk/graphql/request.ts
  src/sdk/product/useProduct.ts
  src/sdk/product/useProductsQuery.ts
  src/sdk/search/useSuggestions.ts
  src/sdk/search/useTopSearch.ts
  src/sdk/session/validate.ts
  yarn.lock
Labels: enhancement

#129 Chore: storybook improvements
  .storybook/main.js
  .storybook/preview.js
  .storybook/storybook.css
  CHANGELOG.md
  src/components/ui/Checkbox/Checkbox.stories.mdx
  src/components/ui/Radio/Radio.stories.mdx
  src/components/ui/Toggle/Toggle.stories.mdx
  src/stories/changelog-template.stories.mdx
  src/stories/colors.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/icons.stories.mdx
  src/stories/theming.stories.mdx
  src/stories/typography.stories.mdx
Labels: enhancement, chore

#135 chore: Remove logo from code
  .storybook/theme.js
  CHANGELOG.md
  public/logo.svg
  src/components/common/Footer/Footer.tsx
  src/components/ui/Logo/Logo.tsx
Labels: performance

#136 chore: Upgrade to 1.9.10
  next.config.js
  package.json
  yarn.lock
Labels: performance

#121 feat: `PriceRange` filter on PLP
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  codegen.yml
  cypress/integration/plp.test.js
  package.json
  src/components/search/Filter/Facets.tsx
  src/components/search/Filter/Filter.tsx
  src/components/search/Filter/useFilter.ts
  src/components/search/Sort/Sort.tsx
  src/components/ui/PriceRange/PriceRange.stories.mdx
  src/components/ui/PriceRange/PriceRange.tsx
  src/components/ui/PriceRange/index.ts
  src/components/ui/PriceRange/price-range.module.scss
  src/pages/[...slug].tsx
  src/sdk/graphql/prefetchQuery.ts
  src/sdk/product/useFormattedPrice.ts
  src/sdk/product/useProductsQuery.ts
  yarn.lock
Labels: enhancement

#128 feat: Extract `RegionalizationModal`
  CHANGELOG.md
  src/components/regionalization/RegionalizationModal/RegionalizationModal.stories.mdx
  src/components/regionalization/RegionalizationModal/RegionalizationModal.tsx
  src/components/regionalization/RegionalizationModal/RegionalizationModalContent.tsx
  src/components/regionalization/RegionalizationModal/index.ts
  src/components/regionalization/RegionalizationModal/regionalization-modal-content.module.scss
  src/components/regionalization/RegionalizationModal/regionalization-modal.scss
  src/components/ui/Modal/Modal.stories.mdx
  src/components/ui/Modal/Modal.tsx
  src/components/ui/Modal/index.ts
  src/components/ui/Modal/modal.module.scss
  src/styles/global/components.scss
Labels: enhancement

#132 Fix: `scrollTo` not working on Safari 15.4
  CHANGELOG.md
  src/components/ui/ImageGallery/ImageGallerySelector.tsx
  src/components/ui/ImageGallery/image-gallery-selector.module.scss
Labels: bug

#110 Feat: `Regionalization` Doc Storybook
  .storybook/preview.js
  .storybook/storybook.css
  CHANGELOG.md
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/navbar.scss
  src/components/regionalization/Regionalization.stories.mdx
  src/components/regionalization/RegionalizationBar/RegionalizationBar.stories.mdx
  src/components/regionalization/RegionalizationBar/RegionalizationBar.tsx
  src/components/regionalization/RegionalizationBar/regionalization-bar.module.scss
  src/components/regionalization/RegionalizationBar/regionalization-bar.scss
  src/components/regionalization/RegionalizationButton/RegionalizationButton.tsx
  src/components/regionalization/RegionalizationButton/regionalization-button.scss
  src/components/regionalization/RegionalizationModal/RegionalizationModal.stories.mdx
  src/components/ui/Modal/Modal.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/theming.stories.mdx
  src/styles/global/components.scss
Labels: documentation, enhancement

#143 Feat: Adds tokens to `ImageGallery`
  CHANGELOG.md
  src/components/ui/Image/Image.tsx
  src/components/ui/Image/image.scss
  src/components/ui/ImageGallery/Icons.tsx
  src/components/ui/ImageGallery/ImageGallery.stories.mdx
  src/components/ui/ImageGallery/ImageGallerySelector.tsx
  src/components/ui/ImageGallery/image-gallery-selector.module.scss
  src/components/ui/ImageGallery/image-gallery.module.scss
  src/styles/global/components.scss
  src/styles/global/layout.scss
  src/styles/global/storybook-components.scss
Labels: chore

#130 Feat: Adds tokens to `Accordion`
  CHANGELOG.md
  src/components/common/Footer/footer.scss
  src/components/search/Filter/filter.scss
  src/components/ui/Accordion/Accordion.stories.mdx
  src/components/ui/Accordion/Accordion.tsx
  src/components/ui/Accordion/AccordionItem.stories.mdx
  src/components/ui/Accordion/AccordionItem.tsx
  src/components/ui/Accordion/accordion.module.scss
  src/components/ui/Accordion/accordion.scss
  src/styles/global/components.scss
  src/styles/global/storybook-components.scss
Labels: documentation, enhancement

#144 Feat: Adds tokens to `ProductGrid`
  .storybook/components/BestPractices.tsx
  .storybook/components/BestPracticesRule.tsx
  .storybook/mocks/productGridItems.js
  CHANGELOG.md
  src/components/product/ProductCard/product-card.module.scss
  src/components/product/ProductGrid/ProductGrid.stories.mdx
  src/components/product/ProductGrid/ProductGrid.tsx
  src/components/product/ProductGrid/product-grid.module.scss
  src/components/ui/Alert/Alert.stories.mdx
Labels: documentation, enhancement

#150 Chore: Adjusts facets tokens
  CHANGELOG.md
  src/components/search/Filter/Facets.stories.mdx
  src/components/search/Filter/facets.module.scss
Labels: chore
